config/routes.rb
BonoboBeta::Application.routes.draw do    
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  resources :companysignups

  resources :signups

  get 'login' => 'sessions#new', :as => 'log_in'
  get 'logout' => 'sessions#destroy', :as => 'log_out'
  resources :sessions

  get 'resetpassword' => 'password_resets#new', :as => 'resetpassword'
  get 'changepassword/:id' => 'password_resets#edit', :as => 'changepassword'
  resources :password_resets

  resources :courses
  match '/course/publish/:id' => 'courses#publish', :as => 'course_publish', via: [:get, :post]
  get '/course/settings/:id' => 'courses#settings', :as => 'course_settings'
  post '/course/unpublish/:id' => 'courses#unpublish', :as => 'course_unpublish'

  resources :lessons
  get 'lesson/image/:id' => 'lessons#image', :as => 'lesson_image'
  get 'lesson/publish/:id' => 'lessons#publish', :as => 'lesson_publish'

  resources :videolessons

  resources :media_libraries

  resources :users
  get 'users' => 'users#edit', :as => 'users_edit'
  match '/users/account/' => 'users#account', :as => 'users_bank', via: [:get, :post]

  resources :slide_lessons
  
  #resources :companysignup

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

	layout 'teacher_student_signup'

	def new
		@user = User.new()
		@show_sign_in = true
		@student_signup = params[:student_signup]
	end

	def create
		@user = User.new user_params
		if @user.save
			@user.send_teacher_confirm(params[:student_signup] == 'true')
		else			
			flash.now.notice = @user.errors.full_messages
			render :new
		end
	end

	def edit
		@user = User.find_by_confirm_email_token(params[:id])
		if(params[:student_signup] == 'true')
			session[:user_id] = @user.id
			render 'update'
		elsif 
			@show_sign_in = true
			if @user.confirm_email_sent_at < 7.days.ago || @user.stripe_id
				render :accessdenied			
			end
		end
	end

	def update
		user = User.find(params[:id])
		if(user.stripe_id)
			render :accessdenied
		elsif(params[:id] && params[:stripeToken])
			user = User.find(params[:id])
			recipient = Stripe::Recipient.create(
			  :name => params[:first] + ' ' + params[:last],
	  		  :type => "individual",
	  		  :email => user.email,
	  		  :bank_account => params[:stripeToken],
	  		  :email => user.email
			)		
			user.update_attribute(:stripe_id, recipient.id)
			session[:user_id] = user.id
		elsif params[:skip]
			session[:user_id] = user.id
		end		
	end

	private
	    def user_params
	      params.require(:user).permit(:first, :last, :email, :password, :password_confirmation, :role)
	    end

end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signups/_form.html.erb
<%= form_for @user, url: signups_path, :method => 'post', :data => {:abide => ''}, html: {class: "custom", id: 'signup-form'} do |f| %>
	<%= f.hidden_field :role, :value => User::USER_ROLE %>
	<%= hidden_field_tag :student_signup, @student_signup %>
	<div class="row">
		<div class="large-12 columns">
			<%= f.text_field :email, :placeholder => 'enter your email address', :required => '' %>
			<small class="error">Email is required.</small>
		</div>
	</div>
	<div class="row">
		<div class="large-6 columns">
			<%= f.text_field :first, :placeholder => 'first name', :required => '' %>
			<small class="error">First name is required.</small>
		</div>
		<div class="large-6 columns">
			<%= f.text_field :last, :placeholder => 'last name', :required => '' %>
			<small class="error">Last name is required.</small>
		</div>
	</div>
	<div class="row">
		<div class="large-6 columns">
			<%= f.password_field :password, :placeholder => 'enter your password', :required => '' %>
			<small class="error">Passwords must be at least 8 characters, one number or special character.</small>
		</div>
		<div class="large-6 columns">
			<%= f.password_field :password_confirmation, :placeholder => 're-enter password', :data => {:equalto => 'user_password'}, :required => '' %>
			<small class="error" data-error-message="">Passwords must match.</small>
		</div>
	</div>
	<section>
		<div class="row">
			<div class="large-12 columns">
				<ul class="inline-list button-container">
					<li class="right">
						<%= submit_tag 'Continue', :class => 'button large radius primary' %>
						<!--<a href="javascript:void(0);" onclick="$('#signup-form').submit();" class="button large radius primary">Continue</a>-->
					</li>
					<li class="right">
						<%= link_to 'Already have account?', new_session_path, :class=>"link-secondary" %>
					</li>
				</ul>
			</div>
		</div>
	</section>
<% end %>

app/views/signups/accessdenied.html.erb
<section class="content-wrapper">
	<form class="custom">
		<div class="row form-wrapper">
			<div class="large-12 columns">
				<div class="account-type">
					<center>
						<%= image_tag 'badge-teacher.png' %>
					</center>
				</div>	
				<div class="row last-row">
					<div class="large-2 medium-2 hide-for-small columns">
						<%= image_tag 'empty-image.png', :class => 'error' %>
					</div>
					<div class="large-10 medium-10 columns">
						<h3 class="blue">Opps!</h3>
						<p>Something has gone wrong.</p>
					</div>
				</div>
				
			</div>
		</div>
	</form>
</section>

app/views/signups/create.html.erb
<% content_for :title do %>
	Create an account
<% end %>
<section class="content-wrapper">
	<form class="custom">
		<div class="row form-wrapper">
			<div class="large-12 columns">
				<div class="account-type">
					<center>
						<%= image_tag 'badge-teacher.png' %>
					</center>
				</div>	
				<div class="large-8 medium-8 large-centered medium-centered columns">
					<div class="large-12 medium-12 columns">
						<h3 class="blue">Almost there!</h3>
						<p>Next check your email for a link to complete your sign-up process.</p>
					</div>
				</div>
			</div>
		</div>
	</form>
</section>

app/views/signups/edit.html.erb
<% content_for :title do %>
	Bank Account Information
<% end %>
<% content_for(:custom_head) do %>

  <%= javascript_include_tag "https://js.stripe.com/v2/" %>

  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" %>

  <script type="text/javascript">
	  
	  
	  Stripe.setPublishableKey('<%= ENV['PUBLISHABLE_KEY'] %>');

	  var stripeResponseHandler = function(status, response) {
	    var $form = $('#account-form');
	    if (response.error) {
	      // Show the errors on the form
	      $('div.alert > p').text(response.error.message);
	      $('div.alert').show();
	    } else {
	      // token contains id, last4, and card type
	      var token = response.id;
	      // Insert the token into the form so it gets submitted to the server
	      $form.append($('<input type="hidden" name="stripeToken" />').val(token));

	      $("#account_number").attr('disabled', 'disabled');
	      $("#routing_number").attr('disabled', 'disabled');
	      $("#account_number_confirmation").attr('disabled', 'disabled');
	      $("#routing_number_confirmation").attr('disabled', 'disabled');

	      // and submit
	      $form.get(0).submit();
	    }
	  };
	  
	  $(document).ready(function() {
	  	$('#account-form').submit(function(event) {
	      if($(this).find('[data-invalid]').length == 0) {
	      	$("ul.inline-list li a").attr('disabled', true);
	      	Stripe.bankAccount.createToken({
        	country: 'US',
        	routingNumber: $("input[data-stripe='routingNumber']").val(),
        	accountNumber: $("input[data-stripe='accountNumber']").val()
      		}, stripeResponseHandler);
	      	return false;
	      };
	    });	
	  });
  </script>

<% end %>

<section class="content-wrapper">
	<div class="row">
		<div class="large-12 columns">
			<%= render '/alert' %>
		</div>
	</div>
	<%= form_tag(signup_path(@user), method:'patch', class:'custom', id:'account-form', :data => {:abide => ''}) do %>		
		<div class="row form-wrapper">
			<div class="large-12 columns">
				<div class="account-type">
					<center>
						<%= image_tag 'badge-teacher.png' %>
					</center>
				</div>	
				<div class="row">
					<div class="large-10 medium-10 large-offset-2 columns">
						<h3 class="blue">Create & Sell Classes for Free!</h3>
						<p>Tell us where to deliver the money you earn from the sales of your classes.</p>
					</div>
				</div>
				<div class="row">
					<div class="large-4 large-offset-2 columns">
						<%= text_field_tag 'first', nil, :placeholder => 'first name as it appears on bank account', :required => '' %>
						<small class="error">Enter first name on account</small>
					</div>
					<div class="large-2 columns">
					</div>
					<div class="large-4 columns">
						<%= text_field_tag 'last', nil, :placeholder => 'second name as it appears on bank account', :required => '' %>
						<small class="error">Enter last name on account</small>
					</div>
					<div class="large-2 columns">
					</div>
				</div>			
				<div class="row">
					<div class="large-4 medium-6 large-offset-2 columns">
						<label>Account Type</label>
						<%= select_tag :account_type, "<option>Checking</option><option>Savings</option><option>Business</option>".html_safe %>
					</div>
					<div class="large-4 medium-6 columns">
						<label>Currency</label>
						<%= select_tag :currency, "<option>US Dollar</option>".html_safe %>
					</div>
					<div class="large-2 columns">
					</div>
				</div>
				<div class="row last-row">
					<div class="large-4 medium-6 large-offset-2 columns">
						<%= text_field_tag 'account_number', nil, :placeholder => 'account number', :required => '', :'data-stripe' => 'accountNumber' %>
						<small class="error">Account number is required</small>
					</div>
					<div class="large-4 medium-6 columns">
						<%= text_field_tag 'account_number_confirmation', nil, :placeholder => 're-enter account number', :required => '', :'data-equalto' => 'account_number' %>
						<small class="error">Account number doesn't match</small>
					</div>
					<div class="large-2 columns">
					</div>
				</div>							
				<div class="row">
					<div class="large-4 medium-6 large-offset-2 columns">
						<%= text_field_tag 'routing_number', nil, :placeholder => 'routing number', :required => '', :'data-stripe' => 'routingNumber' %>
						<small class="error">Routing number is required</small>
					</div>
					<div class="large-4 medium-6 columns">
						<%= text_field_tag 'routing_number_confirmation', nil, :placeholder => 're-enter routing number', :required => '', :'data-equalto' => 'routing_number'%>
						<small class="error">Routing number doesn't match</small>
					</div>
					<div class="large-2 columns">
					</div>
				</div>
			</div>
		</div>
	<% end %>
</section>
<section>
	<div class="row">
		<div class="large-12 columns">
			<ul class="inline-list button-container">
				<li class="right">
					<a href="javascript:void(0)" onclick="$('#account-form').submit();" class="button large radius primary">Continue</a>
				</li>
				<li class="right">
					<%= link_to 'Skip this step', signup_path(@user, :skip => true), :method=>:patch, :class => 'link-secondary' %>
				</li>
			</ul>
		</div>
	</div>
</section>

app/views/signups/new.html.erb
<% content_for :title do %>
	Create an account
<% end %>
<section class="content-wrapper">
		<% if @user.errors.any? %>
			<div class="row">
				<div class="large-12 columns">
					<div data-alert class="alert-box radius alert">
						<% @user.errors.full_messages.each do |msg| %>
							<p><%= msg %></p>
						<% end %>
						<a href="#" class="close">&times;</a>
					</div>
				</div>
			</div>
		<% end %>
		<div class="row form-wrapper">
			<div class="large-12 columns">
				<div class="account-type">
					<center>
						<%= image_tag 'badge-teacher.png' %>
					</center>
				</div>	
				<div class="row last-row">
					<div class="large-8 medium-8 large-centered medium-centered columns">
						<h3 class="blue">Buy &amp; Sell Online Classes</h3>
						<p>Rethink learning—with Bonobo's online course marketplace, anyone can teach and everyone can learn. </p>
						<%= render 'form' %>
					</div>
				</div>
		</div>
</section>

app/views/signups/update.html.erb
<% content_for :title do %>
	Create an account
<% end %>
<% content_for(:custom_head) do %>  

  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" %>

  <script type="text/javascript">	  
	  $(document).ready(function() {
	  	$('.progress-wrapper').css({
			background: '#9acd2b'
		});
	  });
  </script>

<% end %>

<section class="content-wrapper">
	<div class="row form-wrapper">
		<div class="large-12 columns">
			<div class="account-type">
				<center>					
					<%= image_tag 'badge-teacher.png' %>
				</center>
			</div>	
			<div class="row last-row">
				<div class="large-7 medium-7 columns large-offset-2">
					<h3 class="blue">Congratulations! </h3>
					<p>Your Bonobo account is ready. Let's start learning.</p>
				</div>
				<div class="large-3 medium-3 hide-for-small columns">
					<%= image_tag "success-teacher.png", :class => 'sucess-image' %>
				</div>
			</div>
		</div>
	</div>
</section>
<section>
	<div class="row">
		<div class="large-12 columns">
			<p class="text-center">
				<% if params[:student_signup] %>
					<%= link_to 'Get Started', courses_path, :class => 'button large radius primary' %>
				<% else %>
					<%= link_to 'Get Started', courses_path, :class => 'button large radius primary' %>
				<% end %>
			</p>
		</div>
	</div>
</section>