config/routes.rb
BonoboBeta::Application.routes.draw do    
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  resources :companysignups

  resources :signups

  get 'login' => 'sessions#new', :as => 'log_in'
  get 'logout' => 'sessions#destroy', :as => 'log_out'
  resources :sessions

  get 'resetpassword' => 'password_resets#new', :as => 'resetpassword'
  get 'changepassword/:id' => 'password_resets#edit', :as => 'changepassword'
  resources :password_resets

  resources :courses
  match '/course/publish/:id' => 'courses#publish', :as => 'course_publish', via: [:get, :post]
  get '/course/settings/:id' => 'courses#settings', :as => 'course_settings'
  post '/course/unpublish/:id' => 'courses#unpublish', :as => 'course_unpublish'

  resources :lessons
  get 'lesson/image/:id' => 'lessons#image', :as => 'lesson_image'
  get 'lesson/publish/:id' => 'lessons#publish', :as => 'lesson_publish'

  resources :videolessons

  resources :media_libraries

  resources :users
  get 'users' => 'users#edit', :as => 'users_edit'
  match '/users/account/' => 'users#account', :as => 'users_bank', via: [:get, :post]

  resources :slide_lessons
  
  #resources :companysignup

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base	

	COMPANY_ROLE = 'C'
	USER_ROLE = 'M' #Marketplace

	STANDARD_SMALL = 'SS'
	STANDARD_LARGE = 'SL'
	PREMIUM_SMALL = 'PS'
	PREMIUM_LARGE = 'PL'

	has_secure_password

	validates_presence_of :password, :on => :create
	validates_presence_of :role, :on => :create
	validates_uniqueness_of :email, :message => 'already used by other user'

	def send_password_reset
		generate_token(:password_reset_token)
		self.password_reset_sent_at = Time.zone.now		
		save!
		UserMailer.password_reset(self).deliver
	end

	def send_teacher_confirm(student_signup)
		generate_token(:confirm_email_token)
		self.confirm_email_sent_at = Time.zone.now
		save!
		UserMailer.teacher_confirm(self, student_signup).deliver
	end

	def send_company_welcome
		UserMailer.company_welcome(self).deliver
	end

	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])	
	end

	def full_name
		first + ' ' + last
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  skip_before_filter  :verify_authenticity_token

  layout 'user'
  
  # GET /users
  # GET /users.json
  def index
    @user = current_user
  end

  def account 
    @user = current_user

    if (params[:stripeToken])
      token = params[:stripeToken]
      recipient = Stripe::Recipient.create(
        :name => params[:first_name] + ' ' + params[:last_name],
        :type => "individual",
        :bank_account => token,
        :email => current_user.email
        )
      @user.stripe_id = recipient.id
      @user.save
    end

    flash[:alert]= 'Successfully added Bank Account added'
    redirect_to users_edit_path
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @users = current_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bankAccountForm.html.erb
  <script type="text/javascript">
    
    Stripe.setPublishableKey('<%= ENV['PUBLISHABLE_KEY'] %>');

    var stripeResponseHandler = function(status, response) {
      var $form = $('#bank-form');
      if (response.error) {
        // Show the errors on the form
        $('div.alert > p').text(response.error.message);
        $('div.alert').show();
      } else {
        // token contains id, last4, and card type
        var token = response.id;
        // Insert the token into the form so it gets submitted to the server
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));

        $("#account_number").attr('disabled', 'disabled');
        $("#routing_number").attr('disabled', 'disabled');
        $("#account_number_confirmation").attr('disabled', 'disabled');
        $("#routing_number_confirmation").attr('disabled', 'disabled');

        // and submit
        $form.get(0).submit();
      }
    };
    
    $(document).ready(function() {
      $('#bank-form').submit(function(event) {
        if($(this).find('[data-invalid]').length == 0) {
          $("ul.inline-list li a").attr('disabled', true);
          Stripe.bankAccount.createToken({
          country: 'US',
          routingNumber: $("input[data-stripe='routingNumber']").val(),
          accountNumber: $("input[data-stripe='accountNumber']").val(),
          }, stripeResponseHandler);
          return false;
        };
      }); 
    });
  </script>







   <div id="bank-added-label">
      <div class="row">
        <div class="large-2 medium-2 columns">
          <label class="top-border">Bank Account<label>
        </div>
        <div class="large-10 columns">
         <% if @user.stripe_id? %>
             <p class="gray">Added<span class="right"><a id="change-bank-info" class="button small secondary radius">Change</a></span></p>
          <% else %>
             <p class="gray"><span class="right"><a id="change-bank-info" class="button small secondary radius">Add Bank Account</a></span></p>
          <% end %>
        </div>
      </div>
    </div>


  <%= form_tag(users_bank_path, id:'bank-form', :remote => true, :data => {:abide => ''}) do %> 
        <div class="row">
          <div class="large-2 medium-2 columns">
            <label class="top-border">Name on Account<label>
          </div>
          <div class="large-5 columns">
            <%= text_field_tag 'first_name', nil, :placeholder => 'first name as it appears on account', :required => '' %>
            <small class="error">First Name is required</small>
          </div>
          <div class="large-5 columns">
            <%= text_field_tag 'last_name', nil, :placeholder => 'last name as it appears on account', :required => '' %>
            <small class="error">Last Name is required</small>
          </div>
        </div>
        <div class="row">
          <div class="large-2 medium-2 columns">
            <label class="top-border">Name of Bank<label>
          </div>
          <div class="large-10 columns">
            <%= text_field_tag 'bank', nil, :placeholder => 'Name of Bank', :required => '' %>
            <small class="error">Bank Name is required</small>
          </div>
        </div>
        <div class="row">
          <div class="large-2 medium-2 columns">
            <label class="top-border">Account Details<label>
          </div>
          <div class="large-5 medium-5 columns">
            <label>Account Type</label>
            <%= select_tag :account_type, "<option>Checking</option><option>Savings</option><option>Business</option>".html_safe %>
          </div>
          <div class="large-5 medium-5 columns">
            <label>Currency</label>
            <%= select_tag :currency, "<option>US Dollar</option>".html_safe %>
          </div>
        </div>
        <div class="row">
           <div class="large-2 medium-2 columns">
             <label class="top-border">Account Number<label>
           </div>
           <div class="large-5 medium-5 columns">
             <%= text_field_tag 'account_number', nil, :placeholder => 'account number', :required => '', :'data-stripe' => 'accountNumber' %>
              <small class="error">Account number is required</small>
           </div>
           <div class="large-5 medium-5 columns">
              <%= text_field_tag 'account_number_confirmation', nil, :placeholder => 're-enter account number', :required => '', :'data-equalto' => 'account_number' %>
              <small class="error">Account number doesn't match</small>
           </div>
        </div>
          <div class="row last-row">
            <div class="large-2 medium-2 columns">
              <label class="top-border">Routing Number<label>
            </div>
            <div class="large-5 medium-5 columns">
              <%= text_field_tag 'routing_number', nil, :placeholder => 'routing number', :required => '', :'data-stripe' => 'routingNumber' %>
              <small class="error">Routing number is required</small>
            </div>
            <div class="large-5 medium-5 columns">
              <%= text_field_tag 'routing_number_confirmation', nil, :placeholder => 're-enter routing number', :required => '', :'data-equalto' => 'routing_number'%>
              <small class="error">Routing number doesn't match</small>
            </div>
          </div>
          <button class="button primary radius medium right" onclick="$('#account-form').submit();">Save</buton>
  <% end %>

app/views/users/_bioForm.html.erb
<form>
	<div class="row">
		<div class="large-2 medium-2 columns">
			<label class="top-border">Picture<label>
		</div>
		<div class="large-10 medium-10 columns">
			<div class="clearfix" style="margin-bottom:20px; ">
				<img src="assets/images/teacher-profile-image-thumb.png" class="left">
				<input type="file" id="imageUpload" class="button secondary radius small left" style="width:auto; background:transparent;">
			</div>
		</div> 
	</div>
	<div class="row">
		<div class="large-2 medium-2 columns">
			<label class="top-border">Name<label>
		</div>
		<div class="large-5 medium-5 columns">
			<input type="text" id="lesson-title" placeholder="first">
		</div>
		<div class="large-5 medium-5 columns">
			<input type="text" id="lesson-title" placeholder="last">
		</div>  
	</div>
	<div class="row">
		<div class="large-2 medium-2 columns">
			<label class="top-border">Bonobo Address<label>
		</div>
		<div class="large-5 medium-5 columns">
			<input type="text" id="url-prefix" placeholder="" value="https://www.bonobolearning.com/category/" disabled class="url-prefix">
		</div>
		<div class="large-5 medium-5 columns">
			<input type="text" id="url" placeholder="" value="username">
		</div>   
	</div>
	<div class="row">
		<div class="large-2 medium-2 columns">
			<label class="top-border">Experience<label>
		</div>
		<div class="large-10 medium-10 columns">
			<select>
	          <option value="starbuck">1 Year</option>
	          <option value="hotdog">2 Years</option>
	          <option value="apollo">3 Years</option>
	          <option value="apollo">4 Years</option>
	          <option value="apollo">4 Years</option>
	          <option value="apollo">5 Years</option>
	          <option value="apollo">6 Years</option>
	          <option value="apollo">7 Years</option>
	          <option value="apollo">7+ Years</option>
	        </select>
		</div>
	</div>
	<div class="row">
		<div class="large-2 medium-2 columns">
			<label class="top-border">Bio<label>
		</div>
		<div class="large-10 medium-10 columns">
			<textarea placeholder="enter a description of your expertise in this subject..."></textarea>
		</div> 
	</div>
	<div class="row">
		<div class="large-2 medium-2 columns">
			<label class="top-border">Website<label>
		</div>
		<div class="large-10 medium-10 columns">
			<input type="text" id="url" placeholder="enter your web site url">
		</div> 
	</div>
	<div class="row">
		<div class="large-2 medium-2 columns">
			<label class="top-border">Facebook<label>
		</div>
		<div class="large-10 medium-10 columns">
			<input type="text" id="url" placeholder="enter your facebook page url">
		</div> 
	</div>
	<div class="row">
		<div class="large-2 medium-2 columns">
			<label class="top-border">Twitter<label>
		</div>
		<div class="large-10 medium-10 columns">
			<input type="text" id="url" placeholder="enter your twitter page url">
		</div> 
	</div>	
	<button class="button primary radius medium right">Save</buton>
</form>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td> <%= @user.email %> </td>
        <td><%= link_to 'Show', @user %></td>
        <td><%= link_to 'Edit', edit_user_path(@user) %></td>
        <td><%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>