config/routes.rb
BonoboBeta::Application.routes.draw do    
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  resources :companysignups

  resources :signups

  get 'login' => 'sessions#new', :as => 'log_in'
  get 'logout' => 'sessions#destroy', :as => 'log_out'
  resources :sessions

  get 'resetpassword' => 'password_resets#new', :as => 'resetpassword'
  get 'changepassword/:id' => 'password_resets#edit', :as => 'changepassword'
  resources :password_resets

  resources :courses
  match '/course/publish/:id' => 'courses#publish', :as => 'course_publish', via: [:get, :post]
  get '/course/settings/:id' => 'courses#settings', :as => 'course_settings'
  post '/course/unpublish/:id' => 'courses#unpublish', :as => 'course_unpublish'

  resources :lessons
  get 'lesson/image/:id' => 'lessons#image', :as => 'lesson_image'
  get 'lesson/publish/:id' => 'lessons#publish', :as => 'lesson_publish'

  resources :videolessons

  resources :media_libraries

  resources :users
  get 'users' => 'users#edit', :as => 'users_edit'
  match '/users/account/' => 'users#account', :as => 'users_bank', via: [:get, :post]

  resources :slide_lessons
  
  #resources :companysignup

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	
	VIDEO_LESSON = 'V'
	QUIZ_LESSON = 'Q'
	SLIDE_LESSON = 'S'

	belongs_to :course

	has_many :lesson_resources
	has_many :media_libraries, through: :lesson_resources
	has_many :lesson_slides
	accepts_nested_attributes_for :lesson_slides

	def lessonType
		if(self.lesson_type == VIDEO_LESSON)
			'Video'
		elsif(self.lesson_type == QUIZ_LESSON)
			'Quiz'
		else
			'Slides'
		end
	end
	
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

	layout 'courses'

	def index
		@user = current_user
		@course = Course.find(params[:course_id])
		@lessons = Lesson.where(:course => @course, :active => true)
		@new_course_success = params[:new_course_success]
		@new_lesson_success = params[:new_lesson_success]
	end

	def destroy
		lesson = Lesson.find(params[:id])
		lesson.active = false
		lesson.save
		respond_to do |format|
			format.js { @lesson = lesson }
		end
	end

	def publish
		lesson = Lesson.find(params[:id])
		lesson.published = true
		lesson.save
		respond_to do |format|
			format.js { @lesson = lesson }
		end
	end

	def image
		@media_library = MediaLibrary.find(params[:id])
		render :layout => false 
	end
	
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_add_resource.html.erb
<div id="add-resources" class="reveal-modal small" data-reveal="">
  	<h2>Add Resources</h2>
  	<dl class="tabs" data-tab="">
		<dd class="active"><a href="#panel2-1">Media Library</a></dd>
		<dd><a href="#panel2-2">Links</a></dd>
	</dl>
	<div class="tabs-content">
		<div class="content active" id="panel2-1">
			<div id="drop-zone">
				<h4 class="text-center">Drag N' Drop<br><small>or</small></h4>
				<p class="text-center">
					<%= form_tag media_libraries_path, :remote => true, :method => 'post', html: {:class => "custom", :multipart => true} do %>
						<%= hidden_field_tag :user_id, @course.user_id %>
						<%= file_field_tag :file_name, :class=>"button secondary radius small", :style=>"width:intrinsic;" %>
					<% end %>
				</p>
			</div>
			<h6>Select Media From Your Library</h6>
			<ul class="media-list">
				<% @resources.each do |resource| %>
					<% if @lesson_media_resources && @lesson_media_resources.include?(resource) %>
						<li class="selected" id="<%= resource.id %>"><%= resource.name %></li>
					<% else %>
						<li id="<%= resource.id %>"><%= resource.name %></li>
					<% end %>
				<% end %>
			</ul>	
  		</div>
		<div class="content" id="panel2-2">
			<%= form_tag media_libraries_path, :remote => true, :data => {:abide => ''}, :method => 'post', html: {:class => "custom"} do %>
				<%= hidden_field_tag :user_id, @course.user_id %>
				<%= text_field_tag :link, nil, :placeholder => 'enter the url', :required => '', :pattern=>'url' %>
				<small class="error">Please provide valid url</small>
			<% end %>
	  		<a href="javascript:void(0);" onclick="addLink();" target="new" class="button small radius secondary">Add Link</a>
	  		<h6>Links to Resources</h6>
	  		<ul class="media-list">
				<% @links.each do |resource| %>
					<% if @lesson_media_resources && @lesson_media_resources.include?(resource) %>
						<li class="selected" id="<%= resource.id %>"><%= resource.link %></li>
					<% else %>
						<li id="<%= resource.id %>"><%= resource.link %></li>
					<% end %>
				<% end %>
			</ul>
		</div>	
	</div>
  	<a href="javascript:void(0);" class="button radius small primary right" onclick="done();">Done</a>
  	<a class="close-reveal-modal">×</a>
</div>

<script type="text/javascript">
	function addLink() {
		$("div#panel2-2 > form").submit();
		enabledUpdateButton();
	}

	function done() {
		$('a.close-reveal-modal').trigger('click');
		var resourceCounter = $("input[name*='media_library_ids']").size()
		if(resourceCounter > 0) {
			$("div.alert > p").html('Added ' + resourceCounter + ' resources to this lesson.').parent().show();
			enabledUpdateButton();			
		}
	}
</script>

app/views/lessons/destroy.js.erb
$("ul#lesson-<%= @lesson.id %>").remove()
$("div.success > p").html('Lesson has been removed');
$("div.success").removeAttr('style');

app/views/lessons/image.html.erb
<%= image_tag @media_library.file_name_url.to_s, :id => 'cover_preview', :style => 'height:800px; width:800px;' %>

app/views/lessons/index.html.erb
<% content_for(:custom_head) do %>
	<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" %>
<% end %>

<div class="large-2 medium-2 columns hide-for-small-only left-sub-nav" style="height: 493px;">
	<h4>Add A Lesson</h4>
	<p class="note">Click a lesson type below to add it to your syllabus.</p>
	<ul id="add-lesson-menu" class="side-nav">
		<li id="video-bu"><%= link_to 'Video', new_videolesson_path(:course_id => @course.id) %></li>
		<li id="slideshow-bu"><%= link_to 'Slide Show', new_slide_lesson_path(:course_id => @course.id) %></li>
	</ul>
</div>

<div class="large-8 medium-8 small-12 columns">
	<div class="conent-wrapper">
		<%= render '/alert' %>
		<%= render '/success' %>
		<h1>Course Syllabus</h1>
		<div class="hide-for-medium-up">
			<label class="top-border">Add A Lesson<label>
			<select>
				<option>select a lesson type</option>
				<option>Video</option>
				<option>Slide Show</option>
				<option>Quiz</option>
			</select>
		</label></label></div>
		<form>
			<div class="row">
				<div class="large-2 medium-2 columns">
					<label class="top-border">Lesson Order<label>
				</label></label></div>
				<div class="large-10 medium-10 columns" style="margin-top:10px;">
					<input id="checkbox1" type="checkbox"><label for="checkbox1">Make learners complete your course in the order you set below.</label>
				</div> 
			</div>
			<div class="table-wrapper">
				<ul class="inline-list table-header">
					<li>Lesson Name</li>
					<li class="type">Type</li>
					<li class="completed">Status</li>
					<li class="remove">Remove</li>
				</ul>
				<% @lessons.each do |lesson| %>
					<ul id="lesson-<%= lesson.id %>" class="table ui-sortable">
					  	<li class="<% if !lesson.published %>not-published<%else%>ui-state-default<%end%>">
						  	<ul class="inline-list">
						  		<% if lesson.lesson_type == Lesson::SLIDE_LESSON %>
						  			<li><%= link_to lesson.title, edit_slide_lesson_path(lesson) %></a></li>
						  		<% else %>
						  			<li><%= link_to lesson.title, edit_videolesson_path(lesson) %></a></li>
						  		<% end %> 
						  		<li class="type"><%= lesson.lessonType %></li>
						  		<li class="completed">
						  			<% if lesson.course.published && lesson.published %>
						  				Live
						  			<% elsif lesson.course.published && !lesson.published %>
						  				<%= link_to 'Publish', lesson_publish_path(lesson), :class => 'button tiny round simple', remote: true, :id => 'publish_lesson' %>
						  			<% else %>
						  				Draft
						  			<% end %>
						  		</li>
						  		<li class="remove">
						  			<%= link_to lesson_path(lesson), :method => :delete, :remote => true, :id => "lesson-remove-" + lesson.id.to_s do %>
						  				<span></span>
						  			<% end %>
						  		</li>
						  	</ul>
						</li>				  
					</ul>
				<% end %>
			</div>
		</form>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('.light-side-nav-wrapper').find("#lessons").addClass('active');
		$('.light-side-nav-wrapper').find("#lessons").addClass('has-sub-nav');
     	$('#global-nav').find("#courses").addClass('active');

     	<% if @new_course_success %>
     		$("div.success > p").html("Course has been created").parent().show();
     	<% end %>

		<% if @new_lesson_success %>
     		$("div.success > p").html("Lesson has been created").parent().show();
     	<% end %>

     	$("li.remove > a").click(function(event) {
     		var result = confirm('Are you sure you want to delete this lesson?');
			if(result) {
				return true;
			} else {
				event.preventDefault();
				return false
			}
     	});
	});
</script>

app/views/lessons/publish.js.erb
$("div.success > p").html('Lesson has been published');
$("div.success").removeAttr('style');
$("ul#lesson-<%= @lesson.id %>").find("a#publish_lesson").replaceWith('Live');