config/routes.rb
BonoboBeta::Application.routes.draw do    
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  resources :companysignups

  resources :signups

  get 'login' => 'sessions#new', :as => 'log_in'
  get 'logout' => 'sessions#destroy', :as => 'log_out'
  resources :sessions

  get 'resetpassword' => 'password_resets#new', :as => 'resetpassword'
  get 'changepassword/:id' => 'password_resets#edit', :as => 'changepassword'
  resources :password_resets

  resources :courses
  match '/course/publish/:id' => 'courses#publish', :as => 'course_publish', via: [:get, :post]
  get '/course/settings/:id' => 'courses#settings', :as => 'course_settings'
  post '/course/unpublish/:id' => 'courses#unpublish', :as => 'course_unpublish'

  resources :lessons
  get 'lesson/image/:id' => 'lessons#image', :as => 'lesson_image'
  get 'lesson/publish/:id' => 'lessons#publish', :as => 'lesson_publish'

  resources :videolessons

  resources :media_libraries

  resources :users
  get 'users' => 'users#edit', :as => 'users_edit'
  match '/users/account/' => 'users#account', :as => 'users_bank', via: [:get, :post]

  resources :slide_lessons
  
  #resources :companysignup

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	
	skip_before_filter  :verify_authenticity_token

	def index
		@user = current_user
		@courses = Course.where(:user_id => @user.id)
		render :layout => 'course_landing'
	end

	def new
		@course = Course.new()
		@user = current_user
	end

	def create
		@course = Course.create(course_params)
		@user = current_user
		redirect_to lessons_path(:course_id => @course.id, :new_course_success => true)
	end

	def update
		@course = Course.find(params[:id])
		@course.update_attributes(course_params)
		@course.save
		respond_to do |format|
			format.js {}
		end
	end

	def show
		@course = Course.find(params[:id])
		@user = current_user
		@lessons = Lesson.where(:course => @course, :active => true)
	end

	def syllabus
		
	end

	def publish
		course = Course.find(params[:id])
		@user = User.find(params[:userId])

		course.published = true
		course.save
		lessons = Lesson.where(:course => course)
		lessons.each do |lesson|
			lesson.published = true
			lesson.save
		end
		
		respond_to do |format|
			format.js { @updated_at = course.updated_at.strftime("%a %b %d %Y") }
		end
	end

	def settings
		@user = current_user
		@course = Course.find(params[:id])
		@lessons = Lesson.where(:course => @course, :active => true)
	end

	def unpublish
		@user = current_user
		@course = Course.find(params[:id])
		@course.published = false
		@course.save
		@lessons = Lesson.where(:course => @course, :active => true)
		@lessons.each do |lesson|
			lesson.published = false
			lesson.save
		end
		redirect_to course_settings_path(@course)
	end

	private
	    def course_params
	      params.require(:course).permit(:title, :description, :course_category_id, :course_level_id, :user_id, :cover_image, :hero_image)
	    end
	
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_bank_modal.html.erb
  <script type="text/javascript">
    
    
    Stripe.setPublishableKey('<%= ENV['PUBLISHABLE_KEY'] %>');

    var stripeResponseHandler = function(status, response) {
      var $form = $('#account-form');
      if (response.error) {
        // Show the errors on the form
        $('div.alert > p').text(response.error.message);
        $('div.alert').show();
      } else {
        // token contains id, last4, and card type
        var token = response.id;
        // Insert the token into the form so it gets submitted to the server
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));

        $("#account_number").attr('disabled', 'disabled');
        $("#routing_number").attr('disabled', 'disabled');
        $("#account_number_confirmation").attr('disabled', 'disabled');
        $("#routing_number_confirmation").attr('disabled', 'disabled');

        // and submit
        $form.get(0).submit();
      }
    };
    
    $(document).ready(function() {
      $('#account-form').submit(function(event) {
        if($(this).find('[data-invalid]').length == 0) {
          $("ul.inline-list li a").attr('disabled', true);
          Stripe.bankAccount.createToken({
          country: 'US',
          routingNumber: $("input[data-stripe='routingNumber']").val(),
          accountNumber: $("input[data-stripe='accountNumber']").val(),
          }, stripeResponseHandler);
          return false;
        };
      }); 
    });
  </script>

<div id="bank-modal" class="reveal-modal medium" data-reveal>
  <div class="large-12 columns">
    <%= render '/alert' %>
  </div>
     
  <%= form_tag(course_publish_path(@course), id:'account-form', :remote => true, :data => {:abide => ''}) do %> 
      <%= hidden_field_tag 'userId', @user.id %>
    <div class="row form-wrapper">
      <div class="large-12 columns">
        <div class="account-type">
          <center>
            <%= image_tag 'badge-teacher.png' %>
          </center>
        </div>  
        <div class="row">
          <div class="large-10 medium-10 large-offset-2 columns">
            <h3 class="blue">Create & Sell Classes for Free!</h3>
            <p>Tell us where to deliver the money you earn from the sales of your classes.</p>
          </div>
        </div>
        <div class="row">
          <div class="large-8 large-offset-2 columns">
            <%= text_field_tag 'name', nil, :placeholder => 'name as it appears on bank account', :required => '' %>
            <small class="error">Name is required</small>
          </div>
          <div class="large-2 columns">
          </div>
        </div>      
        <div class="row">
          <div class="large-4 medium-6 large-offset-2 columns">
            <label>Account Type</label>
            <%= select_tag :account_type, "<option>Checking</option><option>Savings</option><option>Business</option>".html_safe %>
          </div>
          <div class="large-4 medium-6 columns">
            <label>Currency</label>
            <%= select_tag :currency, "<option>US Dollar</option>".html_safe %>
          </div>
          <div class="large-2 columns">
          </div>
        </div>
        <div class="row last-row">
          <div class="large-4 medium-6 large-offset-2 columns">
            <%= text_field_tag 'account_number', nil, :placeholder => 'account number', :required => '', :'data-stripe' => 'accountNumber' %>
            <small class="error">Account number is required</small>
          </div>
          <div class="large-4 medium-6 columns">
            <%= text_field_tag 'account_number_confirmation', nil, :placeholder => 're-enter account number', :required => '', :'data-equalto' => 'account_number' %>
            <small class="error">Account number doesn't match</small>
          </div>
          <div class="large-2 columns">
          </div>
        </div>              
        <div class="row">
          <div class="large-4 medium-6 large-offset-2 columns">
            <%= text_field_tag 'routing_number', nil, :placeholder => 'routing number', :required => '', :'data-stripe' => 'routingNumber' %>
            <small class="error">Routing number is required</small>
          </div>
          <div class="large-4 medium-6 columns">
            <%= text_field_tag 'routing_number_confirmation', nil, :placeholder => 're-enter routing number', :required => '', :'data-equalto' => 'routing_number'%>
            <small class="error">Routing number doesn't match</small>
          </div>
          <div class="large-2 columns">
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="large-12 columns">
      <ul class="inline-list button-container">
        <li class="right">
          <a onclick="$('#account-form').submit();$('#bank-modal').foundation('reveal', 'close');" class="button large radius primary">Save</a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/courses/_course_published_success.html.erb
<div id="published" data-alert class="alert-box radius success" style="display:none">
	<p>Course has been published</p>
	<a href="#" class="close">&times;</a>
</div>

app/views/courses/_create.html.erb
<%= form_for @course, :remote => true, :method => 'patch', :data => {:abide => ''}, html: {:class => "custom", :multipart => true, :id => 'existing_course'} do |f| %>
			
	<%= render 'formContent', :f => f %>

	<% if @course.published %>
		<a data-reveal-id="update-modal" class="button primary radius medium right">Save</a>
	<% elsif %>
		<button class="button primary radius medium right">Save</button>
	<% end %>
<% end %>

<script type="text/javascript">
	$(document).ready(function() {
		$('#course_cover_image').attr('onchange', "previewImage('course_cover_image', 'cover_preview');");
		$('#course_hero_image').attr('onchange', "previewImage('course_hero_image', 'hero_preview');");
	})
</script>

app/views/courses/_jquery.html.erb
<script type="text/javascript">
	function updateCountdown() {
    	var remaining = 140 - $('textarea#course_description').val().length;
    	if(remaining < 10) {
			$('span#charactersLeft').css('color', 'red');
    		$('span#charactersLeft').text(remaining);
    	} else {
    		$('span#charactersLeft').removeAttr('style');
    		$('span#charactersLeft').text(remaining);
    	}
	}

	function previewImage(fileUploadInput, previewImg) {
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById(fileUploadInput).files[0]);

        oFReader.onload = function (oFREvent) {
            document.getElementById(previewImg).src = oFREvent.target.result;
        };
    };

	$(document).ready(function() {
		$('textarea#course_description').on('input', updateCountdown);
		$('.light-side-nav-wrapper').find("#details").addClass('active');
     	$('#global-nav').find("#courses").addClass('active');
	});
</script>

app/views/courses/_no_bank_account.html.erb
<div id="no-bank-account" class="reveal-modal medium" data-reveal>
		<center>
			<svg version="1.1" id="bonobo_teacher" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 189 189" enable-background="new 0 0 189 189" xml:space="preserve">
				<circle fill="#88D2D3" cx="94.5" cy="94.5" r="94.5"/>
					<g>
						<path fill="#5A4E6D" d="M142.6,62.6c-7.9-14.6-22.2-25.2-39.2-28c-1.4-7.2-6.8-13-13.9-14.9c3.2,6.7,0,12.1-4.7,14.7
							c1.2-2.6,1.9-5.4,2.2-8.3c-2.3,4.2-5.9,7.7-10.4,10.1c-1.1,0.6-2.1,1.2-3,1.8C62,42.8,52.4,51.5,46.4,62.6
							c-14,0.2-25.3,11.6-25.3,25.6c0,13.8,10.9,25.1,24.6,25.6c0.4,3.8,1.6,7.5,3.6,10.8c-0.2-1.6-0.2-3.3-0.1-5c1.2,3.2,3,6.1,5.3,8.6
							c-0.4-1.2-0.7-2.4-1-3.7c5.1,5.8,11.5,10.6,18.7,13.8c4.7,8.9,14,14.7,24.5,14.7c1.6,0,3.2-0.1,4.8-0.4c9.9-1.8,17.7-8.6,21.1-17.4
							c4.8-2.9,9.1-6.5,12.8-10.7c-0.2,1.2-0.5,2.5-1,3.7c2.3-2.5,4.1-5.4,5.3-8.6c0.1,1.7,0.1,3.3-0.1,5c2-3.3,3.2-7,3.6-10.8
							c13.7-0.5,24.6-11.8,24.6-25.6C167.8,74.1,156.6,62.8,142.6,62.6z"/>
						<path fill="#FFFFFF" d="M133.7,98.4c0-13.2-9.8-25.4-23.4-25.4c-4,0-6.9,0.8-9.4,1.8c-2.1,0.8-4,1.6-6.5,1.6s-4.3-0.7-6.5-1.6
							c-2.5-1-5.3-1.8-9.4-1.8c-16.3,0-23.5,10.7-23.4,25.4c0.6-1.5,1.5-2.9,2.4-4.2c-0.4,2.4-0.4,4.8-0.1,7.1c0.4-1.4,1-2.8,1.7-4.2
							c1.4,7.8,7.6,14,15.4,15.4c-2.9,5-4.1,11.1-3,17.2c2.5,13.9,15.7,23.2,29.6,20.8s23.2-15.7,20.8-29.6c-0.6-3.5-1.9-6.7-3.7-9.5
							c5.9-2.4,10.3-7.8,11.5-14.2c0.7,1.3,1.3,2.8,1.7,4.2c0.4-2.4,0.3-4.8-0.1-7.1C132.3,95.5,133.1,96.9,133.7,98.4z"/>
						<g>
				<path fill="#5A4E6D" d="M111.6,131.6c-1.7,3-4.5,5.4-7.9,6.7c-3.4,1.3-7.1,1.5-10.5,0.6c-3.4-1-6.2-3-7.9-5.7
								c-0.3-0.4-0.2-1,0.2-1.4c0.4-0.4,1-0.6,1.5-0.4c4.4,1.6,9.2,1.5,13.7-0.3c4.5-1.8,8-5,10-9c0.2-0.5,0.8-0.8,1.4-0.8
								c0.6,0,1,0.4,1.2,0.9C113.8,125.3,113.3,128.6,111.6,131.6z"/>
				</g>
					<path fill="#5A4E6D" d="M106.4,101.4c1.3,0,2.5,0.4,3.5,1.2c1.1-0.8,1.9-2.6,1.9-4.6c0-2.8-1.5-5.1-3.4-5.1c-1.9,0-3.4,2.3-3.4,5.1
							c0,1.3,0.3,2.5,0.9,3.4C106,101.4,106.2,101.4,106.4,101.4z"/>
					<path fill="#5A4E6D" d="M79.1,102.6c1-0.7,2.2-1.2,3.5-1.2c0.2,0,0.4,0,0.6,0c0.5-0.9,0.9-2.1,0.9-3.4c0-2.8-1.5-5.1-3.4-5.1
							c-1.9,0-3.4,2.3-3.4,5.1C77.2,100,78,101.7,79.1,102.6z"/>
				<g>
					<path fill="#5A4E6D" d="M64.8,90c0,0,2.1-9.6,13.2-9.6c5,0,7.6,4.7,7.6,4.7s-3.3-2-8-2C68.3,83.2,64.8,90,64.8,90z"/>
				</g>
				<g>
					<path fill="#5A4E6D" d="M118.1,93.9c0,0-0.1-8.9-8.1-8.9c-3.6,0-5.5,3.9-5.5,3.9s1.7-1.5,5-1.5C116.2,87.5,118.1,93.9,118.1,93.9z
								"/>
				</g>
				<g>
					<g>
						<path fill="#5A4E6D" d="M96.8,113.3l2.9-0.5c1-0.2,1.7-1.1,1.6-2.1c-0.2-1-1.1-1.6-2.2-1.4C97.3,109.5,97,111.4,96.8,113.3z"/>
						<path fill="#5A4E6D" d="M89.4,110.9c-1,0.2-1.7,1.1-1.5,2.1c0.2,1,1.1,1.6,2.2,1.4l2.9-0.5C92.2,112.3,91.3,110.6,89.4,110.9z"/>
					</g>
				</g>
			</g>
			<path fill="#FFFFFF" d="M38.5,88c-0.5,2.7-0.5,5.5-0.1,8.2c0.4-1.5,1-2.9,1.7-4.3c0.2,3.7,0.8,7.4,1.8,10.9
						c-6.1-2.1-10.4-7.8-10.4-14.5c0-6.8,4.4-12.6,10.6-14.6c-0.3,1.1-0.6,2.2-0.8,3.2c-3.6,4.6-5.5,10.2-5.4,15.9
						C36.5,91.1,37.4,89.5,38.5,88z"/>
			<path fill="#FFFFFF" d="M147.2,102.7c0.9-3.5,1.6-7.1,1.8-10.9c0.7,1.4,1.2,2.8,1.7,4.3c0.4-2.7,0.4-5.5-0.1-8.2
						c1.1,1.5,2,3.1,2.8,4.8c0-5.7-1.9-11.4-5.4-15.9c-0.2-1.1-0.5-2.2-0.8-3.2c6.1,2,10.6,7.8,10.6,14.6
						C157.6,94.9,153.2,100.6,147.2,102.7z"/>
			<path fill="#EF6A5E" d="M131.6,87.1c-2.5,0-4.7-0.9-7.2-1.9c-1.2-0.5-2.4-1-3.8-1.4c-2.1-0.8-4.5-1.2-7.1-1.2
						c-6,0-10.7,2.1-13.5,5.6c-1.4-1.2-3.3-1.9-5.5-1.9S90.3,87,89,88.2c-2.8-3.5-7.6-5.6-13.5-5.6c-2.6,0-5,0.4-7.1,1.2
						c-1.4,0.4-2.6,1-3.8,1.4c-2.5,1-4.7,1.9-7.2,1.9c-1.3,0-2.3,1-2.3,2.3c0,1.3,1,2.3,2.3,2.3c1,0,1.8-0.1,2.7-0.2
						c-0.6,1.6-1,3.3-1,5.2c0,9,7.3,16.3,16.3,16.3c9,0,16.3-7.3,16.3-16.3c0-1.2-0.1-2.3-0.4-3.4c0,0,0,0,0,0c0-2,2-2.3,3.1-2.3
						s3.1,0.3,3.1,2.3c0,0,0,0,0,0c-0.3,1.1-0.4,2.2-0.4,3.4c0,9,7.3,16.3,16.3,16.3c9,0,16.3-7.3,16.3-16.3c0-1.9-0.3-3.6-1-5.2
						c0.9,0.2,1.8,0.2,2.7,0.2c1.3,0,2.3-1,2.3-2.3C133.9,88.1,132.9,87.1,131.6,87.1z M75.5,108.3c-6.5,0-11.7-5.3-11.7-11.7
						c0-4.6,2.7-7.3,6.1-8.5c1.3-0.4,2.7-0.7,4.2-0.9c0,0,0,0,0.1,0c0.4,0,0.8,0,1.3,0c5.7,0,11.7,2.5,11.7,9.4
						C87.2,103,81.9,108.3,75.5,108.3z M113.5,108.3c-6.5,0-11.7-5.3-11.7-11.7c0-7,6.1-9.4,11.7-9.4c0.4,0,0.9,0,1.3,0c0,0,0,0,0.1,0
						c1.5,0.1,2.9,0.4,4.2,0.9c3.5,1.3,6.1,3.9,6.1,8.5C125.3,103,120,108.3,113.5,108.3z"/>
			</svg>
		</center>
		<h2 class="text-center">Bonobo Alert</h2>
	  	<p class="text-center">Before publishing your class you must add a bank account.</p>
	  	<div class="row">
	  		<div class="large-4 large-centered columns">
	  			<p class="text-center"><%= link_to "Add Account", users_edit_path, :class => "button primary radius small" %></p>
	  		</div>
	  	</div>
	  	<a class="close-reveal-modal">&#215;</a>
	</div>

app/views/courses/index.html.erb
<div class="large-10 medium-10 small-12 columns">
	<div class="conent-wrapper">
		<dl class="tabs" data-tab>
			<dd class="active"><a href="#created">Teaching</a></dd>
			<dd><a href="#purchased">Learning</a></dd>
		</dl>
		<div class="tabs-content tabs-conent-wrapper">
			<div class="content active" id="created">
				<% @courses.each do |course| %>
					<%= link_to course_path(course) do %>
						<div class="course-module">
							<div class="cover-image-wrapper">
								<h6><%= CourseCategory.find(course.course_category_id).name %></h6>
								<%= image_tag course.cover_image_url.to_s, :style => 'height:169px; width:318px;' %>
							</div>
							<%= image_tag 'profile-pic.jpg', :class => 'hide-for-small profile', :style => 'height:66px; width:66px;' %>
							<h4 class="sans">
								<%= link_to course.title, course_path(course), :id => 'course_' + course.id.to_s %>
							</h4>
							<ul class="inline-list">
								<li class="sans stamp">Level: <%= CourseLevel.find(course.course_level_id).name.capitalize %></li>
								<% if course.published %>
									<li class="sans stamp class-published">Status: Published </li>
					    		<% else %>
					    			<li class="sans stamp">Status: Unpublished </li>
					    		<% end %>
							</ul>
						</div>
					<% end %>	
				<% end %>
				<%= link_to new_course_path do %>
					<div class="course-module add-course">
						<h4 class="text-center"><span>+</span><br>Create a Course</h4>
					</div>
				<% end %>
			</div>


			<div class="content" id="purchased">
				
				<a href="courses-profile-template.html">
					<div class="course-module">
						<div class="cover-image-wrapper">
							<h6>Art</h6>
							<img src="content/multi-floral-cover.png">
						</div>
						<img src="content/profile-pic.jpg" class="hide-for-small profile">
						<h4 class="sans"><a href="courses-profile-template.html">Pattern Making 101</a></h4>
						<p class="sans stamp">Level: Beginner</p>
					</div>
				</a>

			</div>

		</div>
	</div>
</div>

app/views/courses/new.html.erb
<% content_for(:custom_head) do %>
	<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" %>
<% end %>
<div class="large-10 medium-10 small-12 columns">
	<div class="content-wrapper">
		<h1 class="course-detail-title">Course Details</h1>
		<div data-alert class="alert-box radius success" style="display:none">
			<p></p>
			<a href="#" class="close">&times;</a>
		</div>
		<%= form_for @course, :url => courses_path, :method => 'post', :data => {:abide => ''}, html: {:class => "custom", :multipart => true} do |f| %>
			
			<%= render 'formContent', :f => f %>
		
			<button class="button primary radius medium right">Next</button>
		<% end %>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('div#light-menu-wrapper').remove();
	});
</script>

<%= render 'jquery' %>

app/views/courses/publish.js.erb
$("a.publish").addClass('disabled');
$("a.publish").text('Publish');
$("div.success > p").html('Course has been published');
$("div.success").removeAttr('style');
$("a.tiny").replaceWith('Live');
$("p.course-status").html('Published');
$("div#status:first").prepend("<span class='unpublish right'><a data-reveal-id='unpublish-modal' class='unpublish button small secondary radius'>Unpublish</a></span>");
$("span.unpublish > a").click(function() {
	$('#update-modal').foundation('reveal', 'open');
});
$("p#time-stamp").html("<%= @updated_at.to_s %>");
$("li.completed").html('Live');

app/views/courses/settings.html.erb
<div class="large-10 medium-10 small-12 columns">
	<div class="conent-wrapper">
		<%= render '/alert' %>
		<%= render '/courses/course_published_success' %>
		<h1 class="course-detail-title">Settings</h1>
		<%= form_tag(course_unpublish_path(@course), :id => 'settings-form') do %>
			<div class="row last">
				<div class="large-2 medium-2 columns">
					<label class="top-border">Class Status<label>
				</label></label></div>
				<div id="status" class="large-10 medium-10 columns">
					<% if @course.published %>
						<span class="unpublish right">
							<a data-reveal-id="unpublish-modal" class="unpublish button small secondary radius" id="unpublish">Unpublish</a>
						</span>
						<p class="gray course-status">Published</p>
					<% elsif %>
						<p class="gray course-status">Unpublished</p>
					<% end %>					
					<p id="time-stamp" class="sans gray"><%= @course.updated_at.strftime("%a %b %d %Y") %></p>
				</div> 
			</div>
			<!--<button class="button primary radius medium right hide">Save</button>-->
		<% end %>
	</div>
</div>

<%= render 'unpublish' %>

app/views/courses/show.html.erb
<% content_for(:custom_head) do %>
	<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" %>
<% end %>

<div class="large-10 medium-10 small-12 columns">
	<div class="conent-wrapper">
		<%= render '/alert' %>
		<h1 class="course-detail-title">Course Details</h1>
		<div data-alert class="alert-box radius success" style="display:none">
			<p></p>
			<a href="#" class="close">&times;</a>
		</div>
		<%= render 'create' %>
	</div>
</div>

<%= render '/courses/alert_update_changes' %>

<%= render 'jquery' %>

app/views/courses/update.js.erb
$("div.success > p").html('Course has been updated').parent().show();